# Generated by Django 4.0.3 on 2022-04-04 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_page', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterModel',
        ),
    ]
