# Generated by Django 4.0.3 on 2022-04-11 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOTP',
        ),
    ]
