# Generated by Django 4.0.3 on 2022-04-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile_no', models.CharField(max_length=15)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date_joined')),
            ],
        ),
    ]
