# Generated by Django 4.0.3 on 2022-04-19 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0002_alter_buyrent_furnished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyrent',
            name='emi',
        ),
    ]
