# Generated by Django 4.0.3 on 2022-04-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0002_visitors'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('choose', models.IntegerField(choices=[(0, 'Complaint'), (1, 'Suggestion')], default=0)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
